name: Build and Release Vial-QMK Firmware for RP2040

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli

    steps:
      - name: Checkout your keymap
        uses: actions/checkout@v4

      - name: Clone vial-qmk
        run: |
          git clone --depth 1 https://github.com/vial-kb/vial-qmk.git vial-qmk
          cd vial-qmk
          git submodule update --init --recursive

      - name: Copy all files except .github to vial-qmk keymap
        run: |
          mkdir -p vial-qmk/keyboards/crkbd/keymaps/halaku-crkbd
          for item in *; do
            if [ "$item" != ".github" ] && [ "$item" != "vial-qmk" ]; then
              cp -r "$item" vial-qmk/keyboards/crkbd/keymaps/halaku-crkbd/
            fi
          done

      - name: Build for RP2040
        run: |
          cd vial-qmk
          qmk compile -c -kb crkbd/rev1 -km halaku-crkbd -e CONVERT_TO=elite_pi

      - name: Prepare firmware artifact
        run: |
          mkdir -p artifact
          cp vial-qmk/.build/crkbd_rev1_halaku-crkbd_elite_pi.uf2 artifact/

      - name: Upload firmware as workflow artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware_rp2040
          path: artifact/crkbd_rev1_halaku-crkbd_elite_pi.uf2

      - name: Create or update GitHub Release and upload firmware
        uses: softprops/action-gh-release@v2
        with:
          name: "Latest Firmware"
          tag_name: "latest"
          files: artifact/crkbd_rev1_halaku-crkbd_elite_pi.uf2
        env:
          GITHUB_TOKEN: ${{ secrets.HAL_KBD }}
